// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./MeetingRoom.sol";
import "./AuraReputation.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title MeetingFactory
 * @notice Factory contract that deploys and tracks MeetingRoom instances.
 *         Records interaction scores to AuraReputation after settlement.
 */
contract MeetingFactory is Ownable {

    AuraReputation public reputationContract;

    // meetingId => MeetingRoom address
    mapping(string => address) public meetings;
    // wallet => list of meeting addresses they participated in
    mapping(address => address[]) public participantMeetings;

    address[] public allMeetings;

    // Protocol fee (in basis points — 100 = 1%)
    uint256 public feeBps = 10; // 0.1%
    address public feeCollector;

    event MeetingCreated(string indexed meetingId, address roomAddress, address creator);
    event MeetingSettledWithReputation(string indexed meetingId, address[] participants);

    constructor(address _reputationContract, address _feeCollector) Ownable(msg.sender) {
        reputationContract = AuraReputation(_reputationContract);
        feeCollector = _feeCollector;
    }

    // ── Factory ───────────────────────────────────────────────────────────────

    /**
     * @notice Deploy a new MeetingRoom contract.
     * @param meetingId Unique ID generated by the API
     * @param participants Array of participant wallet addresses
     */
    function createMeeting(
        string calldata meetingId,
        address[] calldata participants
    ) external returns (address roomAddress) {
        require(meetings[meetingId] == address(0), "MeetingFactory: meetingId exists");
        require(participants.length >= 2, "MeetingFactory: need at least 2 participants");

        MeetingRoom room = new MeetingRoom(meetingId, msg.sender);

        for (uint256 i = 0; i < participants.length; i++) {
            room.addParticipant(participants[i]);
            participantMeetings[participants[i]].push(address(room));
        }

        meetings[meetingId] = address(room);
        allMeetings.push(address(room));

        emit MeetingCreated(meetingId, address(room), msg.sender);
        return address(room);
    }

    /**
     * @notice Called after a meeting settles — updates reputation for all participants.
     * @param meetingId The meeting to settle
     * @param outcomeHash keccak256 of the full transcript + commitments
     * @param participantScores Mapping of participant address to quality score (0–100)
     */
    function settleWithReputation(
        string calldata meetingId,
        bytes32 outcomeHash,
        address[] calldata participants,
        uint256[] calldata scores
    ) external onlyOwner {
        address roomAddress = meetings[meetingId];
        require(roomAddress != address(0), "MeetingFactory: meeting not found");
        require(participants.length == scores.length, "MeetingFactory: length mismatch");

        MeetingRoom room = MeetingRoom(roomAddress);
        room.end();
        room.settle(outcomeHash);

        // Update reputation for each participant
        for (uint256 i = 0; i < participants.length; i++) {
            reputationContract.recordInteraction(
                participants[i],
                AuraReputation.InteractionType.MEETING_COMPLETED,
                scores[i]
            );
        }

        emit MeetingSettledWithReputation(meetingId, participants);
    }

    /**
     * @notice Record a fulfilled commitment — called by the API after human approval.
     */
    function recordCommitmentFulfilled(address agentWallet) external onlyOwner {
        reputationContract.recordInteraction(
            agentWallet,
            AuraReputation.InteractionType.COMMITMENT_FULFILLED,
            100
        );
    }

    /**
     * @notice Record a broken commitment.
     */
    function recordCommitmentBroken(address agentWallet) external onlyOwner {
        reputationContract.recordInteraction(
            agentWallet,
            AuraReputation.InteractionType.COMMITMENT_BROKEN,
            0
        );
    }

    // ── View ──────────────────────────────────────────────────────────────────

    function getMeetingRoom(string calldata meetingId) external view returns (address) {
        return meetings[meetingId];
    }

    function getMeetingsForParticipant(address participant) external view returns (address[] memory) {
        return participantMeetings[participant];
    }

    function totalMeetings() external view returns (uint256) {
        return allMeetings.length;
    }

    // ── Admin ─────────────────────────────────────────────────────────────────

    function setFeeBps(uint256 _feeBps) external onlyOwner {
        require(_feeBps <= 500, "MeetingFactory: fee too high"); // max 5%
        feeBps = _feeBps;
    }

    function setFeeCollector(address _feeCollector) external onlyOwner {
        feeCollector = _feeCollector;
    }
}
